AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0.3
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false

plugins:
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sequel