AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 4.0.3
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Enabled: false
plugins:
  - rubocop-factory_bot
  - rubocop-rake